### PR TITLE
clear serial buffer to provide current meter data

### PR DESCRIPTION
**Pull request by gregeva**
As time passed, I was seeing a larger and larger gap between real meter data and reported meter data.  This is because the FIFO was filling up with the continuous data stream from the meter, however data being read off the stack only periodically (once a minute).

To avoid this, I am flushing the serial input buffer prior to doing the TeleInfo read.

Still certainly not an ideal implementation, but it should more accurate when time stamping and logging energy use data.

### CODE REVIEW

**Comment by akileos** [comment]
Thanks for you pull request, wasn't even aware that someone was using this project :+1: 
I encourage you to switch to the MQTT version which doesn't have delay, every message is directly published to openhab (akileos/TeleQTT).
Will check your PR and merge is ASAP.

**Comment by gregeva** [comment]
Interesting... I have been looking at MQTT and am working getting Mosquitto running on a VM so I will be sure to try out TeleQTT.  Thanks!

... I have been meaning to write an OpenHAB binding for TeleInfo... but don't know Java real well and have other things to do.  Passing it through MQTT is a much more scalable approach!

**Comment by akileos** [comment]
Hehe same here, so much to do & so little time. My Java isn't that good either so I focused on getting things working as cleanly as possible.

**Comment by akileos** [comment]
Thanks for charts, the PR has already been merged into master!
Just being curious, how do you smooth your data ? running average over X minutes ?

**Comment by gregeva** [comment]
The smoothing is meant to take into account the fluctuations on the PAPP reading from the meter which is always bouncing around.  This obviously generates network traffic for the change events even if it isn't really changing, and makes the charts and analysis more difficult.  My goal is to make it clearer while keeping the live data accurate - simplifying database inserts, visualization, etc.

Smoothing being used is very basic; mean value from the last 30 MQTT updates (TeleQTT) which equates to about 1 minute.  It takes a lot of the bounce out.  I tried increasing it to 100 reads, but it smooths off the initial load peak more than I would like.

I saw that you merged the change.  And I have obviously been playing with TeleQTT... and very happy with it and MQTT!!! :-)  Thanks for sharing!

**Comment by akileos** [comment]
Then maybe you can submit a Pull Request for a smoothed PAPP under a different topic in TeleQTT !
Waiting for your pull request ;)

-RB

**Comment by gregeva** [comment]
No can do... it is not a part of the Python scripts.  I have been playing with Node-RED... will eventually share my work as a Gist/Flow when I have logging, calculations, etc. setup.  It's going to be awesome though. ;-)

**Pull request merged**
